<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Abhinav" failures="1" tests="3" name="Test" time="18.902" errors="0" timestamp="2022-07-21T17:18:23 IST">
  <testcase classname="TestClasses.VerifyUserCanLogin" name="verifyUserCanLogin" time="4.135"/>
  <testcase classname="TestClasses.VerifyUserCanAddNewAddress" name="VerifyUserCanGoToProfilePage" time="0.818"/>
  <testcase classname="TestClasses.VerifyUserCanAddNewAddress" name="VerifyUserCanAddAddress" time="7.801">
    <failure type="java.lang.AssertionError" message="expected [1] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [3]
at TestClasses.VerifyUserCanAddNewAddress.VerifyUserCanAddAddress(VerifyUserCanAddNewAddress.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- VerifyUserCanAddAddress -->
</testsuite> <!-- Test -->
